# Generated by Django 3.1.12 on 2021-06-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201110_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='SOME STRING', max_length=500),
        ),
    ]
